package com.atguigu.mybatis.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.did
     *
     * @mbggenerated Sun Apr 03 22:33:18 CST 2022
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.dname
     *
     * @mbggenerated Sun Apr 03 22:33:18 CST 2022
     */
    private String dname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.did
     *
     * @return the value of t_dept.did
     *
     * @mbggenerated Sun Apr 03 22:33:18 CST 2022
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.did
     *
     * @param did the value for t_dept.did
     *
     * @mbggenerated Sun Apr 03 22:33:18 CST 2022
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.dname
     *
     * @return the value of t_dept.dname
     *
     * @mbggenerated Sun Apr 03 22:33:18 CST 2022
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.dname
     *
     * @param dname the value for t_dept.dname
     *
     * @mbggenerated Sun Apr 03 22:33:18 CST 2022
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    public Dept() {
    }

    public Dept(Integer did, String dname) {
        this.did = did;
        this.dname = dname;
    }

    @Override
    public String toString() {
        return "Dept{" +
                "did=" + did +
                ", dname='" + dname + '\'' +
                '}';
    }
}